"""crear historial de indicadores academicos

Revision ID: 793b97805d68
Revises: da1552b4fa45
Create Date: 2026-09-12 00:23:57.380792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793b97805d68'
down_revision = 'da1552b4fa45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('average_grade', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('attendance_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('incidents_count', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('academic_indicators')
    # ### end Alembic commands ###
