"""normalizar personas y relaciones academicas

Revision ID: e81886573fb2
Revises: 88efc6c080aa
Create Date: 2026-09-11 23:02:17.606791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81886573fb2'
down_revision = '88efc6c080aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('students_user_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['person_id'])
        batch_op.drop_constraint(batch_op.f('students_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persons', ['person_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('person_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('teachers_user_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['person_id'])
        batch_op.drop_constraint(batch_op.f('teachers_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'persons', ['person_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('teachers_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('teachers_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('status')
        batch_op.drop_column('person_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('students_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('students_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('status')
        batch_op.drop_column('person_id')

    op.drop_table('persons')
    # ### end Alembic commands ###
